COMPILER=/Applications/Adobe\ Flex\ Builder\ 3/sdks/3.2.0/bin/mxmlc

"$COMPILER" '-sp=../' -optimize Colors.as
"$COMPILER" '-sp=../' -optimize VideoPlayer.as
"$COMPILER" '-sp=../' -optimize ImageLoading.as

# open Colors.swf
# open VideoPlayer.swf
# open ImageLoading.swf